name: Build, Push Docker Image, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: user/repository:latest

    - name: Logout from DockerHub
      run: docker logout

    - name: Run Docker container
      run: |
        docker run -d --name my_app -p 80:80 user/repository:latest

    - name: Check container status
      run: |
        docker ps

    - name: Verify site is live
      run: |
        curl --head http://localhost | grep "200 OK"
